version: '2.4'

services:
  nginx:
    image: nginx:1.21.6
    ports:
      - '8000:8000'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2

  app1:
    build:
      context: ./
      target: dev
    ports:
      - '8001:8000'
    volumes:
      - .:/app
      - /app/node_modules

  app2:
    build:
      context: ./
      target: dev
    ports:
      - '8002:8000'
    volumes:
      - .:/app
      - /app/node_modules
